# Generated by Django 4.1.7 on 2023-03-17 14:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isRestricted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('1', 'Project'), ('2', 'Hackathon')], default='1', max_length=1)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.student')),
            ],
        ),
    ]
