# Generated by Django 4.1.7 on 2023-03-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_student_title_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
